### ISSUE TITLE
audioLights function

### ISSUE THREAD

**Issue by programmeruser517** [programmeruser517/FS23egr100-adaCircuit#4]
where it pulls from an audio file or mic add on and based on the volume spikes, more lights are lit (or brightness is increased, maybe both?) and decreases when volume returns; WILL REQUIRE a library extension for dealing with audio stuff

**Comment by programmeruser517** [comment]
there is no documentable way to do so, but it is clearly possible. I am not spending a whole ass year on this project though. Idea is unfortunately not feasible.

**Comment by Bowenw223** [comment]
Agreed
